"""uuid_schema_all_tables

Revision ID: cfeb49a5c688
Revises: fe783411897f
Create Date: 2026-05-14 12:28:00.129343

"""
from typing import Sequence, Union
from uuid import UUID

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cfeb49a5c688'
down_revision: Union[str, Sequence[str], None] = 'fe783411897f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Stable id for seed row (tests / admin can reference)
SELECT_PERMISSION_TYPE_ID = UUID("33333333-3333-4333-8333-333333333333")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permission_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resources_resource_type', 'resources', ['resource_type'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('access_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_access_logs_accessed_at', 'access_logs', ['accessed_at'], unique=False)
    op.create_index('ix_access_logs_resource_id', 'access_logs', ['resource_id'], unique=False)
    op.create_index('ix_access_logs_user_id', 'access_logs', ['user_id'], unique=False)
    op.create_table('columns',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index('ix_columns_table_id', 'columns', ['table_id'], unique=False)
    op.create_table('databases',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_table('group_roles',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'role_id'),
    sa.UniqueConstraint('group_id', 'role_id', name='uq_group_roles_group_role')
    )
    op.create_index('ix_group_roles_group_id', 'group_roles', ['group_id'], unique=False)
    op.create_index('ix_group_roles_role_id', 'group_roles', ['role_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('permission_type_id', sa.Uuid(), nullable=False),
    sa.Column('effect', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['permission_type_id'], ['permission_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permissions_permission_type_id', 'permissions', ['permission_type_id'], unique=False)
    op.create_index('ix_permissions_resource_id', 'permissions', ['resource_id'], unique=False)
    op.create_table('schemas',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('database_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index('ix_schemas_database_id', 'schemas', ['database_id'], unique=False)
    op.create_table('tables',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('schema_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schema_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index('ix_tables_schema_id', 'tables', ['schema_id'], unique=False)
    op.create_table('user_groups',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_user_groups_user_group')
    )
    op.create_index('ix_user_groups_group_id', 'user_groups', ['group_id'], unique=False)
    op.create_index('ix_user_groups_user_id', 'user_groups', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_role')
    )
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_index('ix_user_roles_user_id', 'user_roles', ['user_id'], unique=False)
    op.create_table('column_masks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('mask_type', sa.String(length=20), nullable=False),
    sa.Column('mask_pattern', sa.Text(), nullable=True),
    sa.CheckConstraint("mask_type IN ('FULL','PARTIAL','HASH','NULLIFY','CUSTOM')", name='ck_column_masks_mask_type'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_id'),
    sa.UniqueConstraint('permission_id', name='uq_column_masks_permission_id')
    )
    op.create_index('ix_column_masks_permission_id', 'column_masks', ['permission_id'], unique=False)
    op.create_table('group_permissions',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'permission_id'),
    sa.UniqueConstraint('group_id', 'permission_id', name='uq_group_permissions')
    )
    op.create_index('ix_group_permissions_group_id', 'group_permissions', ['group_id'], unique=False)
    op.create_index('ix_group_permissions_permission_id', 'group_permissions', ['permission_id'], unique=False)
    op.create_table('permission_change_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=True),
    sa.Column('changed_by', sa.String(length=255), nullable=False),
    sa.Column('change_type', sa.String(length=64), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_perm_change_logs_changed_at', 'permission_change_logs', ['changed_at'], unique=False)
    op.create_index('ix_perm_change_logs_permission_id', 'permission_change_logs', ['permission_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions')
    )
    op.create_index('ix_role_permissions_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_index('ix_role_permissions_role_id', 'role_permissions', ['role_id'], unique=False)
    op.create_table('row_filters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('condition_expr', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_row_filters_permission_id', 'row_filters', ['permission_id'], unique=False)
    op.create_table('user_permissions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('granted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id'),
    sa.UniqueConstraint('user_id', 'permission_id', name='uq_user_permissions')
    )
    op.create_index('ix_user_permissions_permission_id', 'user_permissions', ['permission_id'], unique=False)
    op.create_index('ix_user_permissions_user_id', 'user_permissions', ['user_id'], unique=False)
    op.bulk_insert(
        sa.table(
            "permission_types",
            sa.column("id", sa.Uuid()),
            sa.column("name", sa.String(64)),
        ),
        [{"id": SELECT_PERMISSION_TYPE_ID, "name": "SELECT"}],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_permissions_user_id', table_name='user_permissions')
    op.drop_index('ix_user_permissions_permission_id', table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index('ix_row_filters_permission_id', table_name='row_filters')
    op.drop_table('row_filters')
    op.drop_index('ix_role_permissions_role_id', table_name='role_permissions')
    op.drop_index('ix_role_permissions_permission_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_perm_change_logs_permission_id', table_name='permission_change_logs')
    op.drop_index('ix_perm_change_logs_changed_at', table_name='permission_change_logs')
    op.drop_table('permission_change_logs')
    op.drop_index('ix_group_permissions_permission_id', table_name='group_permissions')
    op.drop_index('ix_group_permissions_group_id', table_name='group_permissions')
    op.drop_table('group_permissions')
    op.drop_index('ix_column_masks_permission_id', table_name='column_masks')
    op.drop_table('column_masks')
    op.drop_index('ix_user_roles_user_id', table_name='user_roles')
    op.drop_index('ix_user_roles_role_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('ix_user_groups_user_id', table_name='user_groups')
    op.drop_index('ix_user_groups_group_id', table_name='user_groups')
    op.drop_table('user_groups')
    op.drop_index('ix_tables_schema_id', table_name='tables')
    op.drop_table('tables')
    op.drop_index('ix_schemas_database_id', table_name='schemas')
    op.drop_table('schemas')
    op.drop_index('ix_permissions_resource_id', table_name='permissions')
    op.drop_index('ix_permissions_permission_type_id', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('ix_group_roles_role_id', table_name='group_roles')
    op.drop_index('ix_group_roles_group_id', table_name='group_roles')
    op.drop_table('group_roles')
    op.drop_table('databases')
    op.drop_index('ix_columns_table_id', table_name='columns')
    op.drop_table('columns')
    op.drop_index('ix_access_logs_user_id', table_name='access_logs')
    op.drop_index('ix_access_logs_resource_id', table_name='access_logs')
    op.drop_index('ix_access_logs_accessed_at', table_name='access_logs')
    op.drop_table('access_logs')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index('ix_resources_resource_type', table_name='resources')
    op.drop_table('resources')
    op.drop_table('permission_types')
    op.drop_table('groups')
    # ### end Alembic commands ###
